/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'DigitalArt' : null } |
  { 'DesignerGoods' : null };
export type MemberTier = { 'Elite' : null } |
  { 'Executive' : null } |
  { 'Standard' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
  'shippingAddress' : string,
  'buyer' : Principal,
}
export type OrderId = bigint;
export type OrderStatus = { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'inStock' : boolean,
  'description' : string,
  'imageUrl' : string,
  'distanceKm' : number,
  'category' : Category,
  'rating' : bigint,
  'cryptoPrice' : [] | [string],
  'price' : bigint,
  'reviewCount' : bigint,
  'tierRequired' : MemberTier,
}
export type ProductId = bigint;
export interface _SERVICE {
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'adminAddProduct' : ActorMethod<
    [
      string,
      string,
      Category,
      bigint,
      [] | [string],
      string,
      boolean,
      MemberTier,
      number,
    ],
    Product
  >,
  'adminUpdateStock' : ActorMethod<[ProductId, boolean], undefined>,
  'getMyMembership' : ActorMethod<[], MemberTier>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[ProductId, bigint, string, string], Order>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'upgradeMembership' : ActorMethod<[MemberTier], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];