/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Category = IDL.Variant({
  'DigitalArt' : IDL.Null,
  'DesignerGoods' : IDL.Null,
});
export const MemberTier = IDL.Variant({
  'Elite' : IDL.Null,
  'Executive' : IDL.Null,
  'Standard' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'inStock' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'category' : Category,
  'rating' : IDL.Nat,
  'cryptoPrice' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'tierRequired' : MemberTier,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'buyer' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'adminAddProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Bool,
        MemberTier,
        IDL.Float64,
      ],
      [Product],
      [],
    ),
  'adminUpdateStock' : IDL.Func([ProductId, IDL.Bool], [], []),
  'getMyMembership' : IDL.Func([], [MemberTier], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Text, IDL.Text],
      [Order],
      [],
    ),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'upgradeMembership' : IDL.Func([MemberTier], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Category = IDL.Variant({
    'DigitalArt' : IDL.Null,
    'DesignerGoods' : IDL.Null,
  });
  const MemberTier = IDL.Variant({
    'Elite' : IDL.Null,
    'Executive' : IDL.Null,
    'Standard' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'inStock' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'category' : Category,
    'rating' : IDL.Nat,
    'cryptoPrice' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'tierRequired' : MemberTier,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'buyer' : IDL.Principal,
  });
  
  return IDL.Service({
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'adminAddProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Bool,
          MemberTier,
          IDL.Float64,
        ],
        [Product],
        [],
      ),
    'adminUpdateStock' : IDL.Func([ProductId, IDL.Bool], [], []),
    'getMyMembership' : IDL.Func([], [MemberTier], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Text, IDL.Text],
        [Order],
        [],
      ),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'upgradeMembership' : IDL.Func([MemberTier], [], []),
  });
};

export const init = ({ IDL }) => { return []; };